//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoHealHealthCare1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AId { get; set; }
        public string AFName { get; set; }
        public string ALName { get; set; }
        public string AContact { get; set; }
        public string AEmail { get; set; }
        public string ASymptoms { get; set; }
        public System.DateTime ADate { get; set; }
        public string RecieptId { get; set; }
        public Nullable<int> AGender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Addrss { get; set; }
        public string City { get; set; }
        public Nullable<int> State1 { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual State State { get; set; }
    }
}
