//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoHealHealthCare1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int CtId { get; set; }
        public string CtName { get; set; }
        public string CtEmail { get; set; }
        public string CtSubject { get; set; }
        public string CtMessage { get; set; }
    }
}
