//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoHealHealthCare1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DId { get; set; }
        public string DName { get; set; }
        public Nullable<int> Dep { get; set; }
        public Nullable<int> Timing { get; set; }
        public Nullable<int> Ward { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Timing Timing1 { get; set; }
        public virtual Ward Ward1 { get; set; }
    }
}
